openapi: 3.0.0
info:
  title: User Registration
  description: Exposes User Registration APIs.
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/users

paths:
  '/':
    post:
      tags:
        - User Registration
      description: |-
        Registers a user
      responses:
        201:
          description: Successful registration
        400:
          description: User already exists or invalid input